# Generated by Django 2.0.5 on 2018-05-08 07:54

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fullname', models.CharField(max_length=10, verbose_name='姓名')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='科目代码')),
                ('name', models.CharField(max_length=20, verbose_name='科目名称')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookedDate', models.DateField(verbose_name='记账日期')),
                ('sn', models.CharField(max_length=15, verbose_name='流水号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('attachmentNo', models.PositiveSmallIntegerField(verbose_name='附件张数')),
                ('accountDetail', models.CharField(blank=True, max_length=50, null=True, verbose_name='科目明细')),
                ('uploaderName', models.CharField(max_length=10, verbose_name='录入人')),
                ('submitted', models.BooleanField(default=False, verbose_name='是否提交')),
                ('confirmed', models.BooleanField(default=False, verbose_name='是否确认')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imgs.Account')),
            ],
            options={
                'ordering': ['-bookedDate', '-sn'],
            },
        ),
        migrations.CreateModel(
            name='CertificateImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadTime', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
                ('img', models.BinaryField(verbose_name='图像数据')),
                ('thumb', models.BinaryField(verbose_name='缩略图')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgs.Certificate')),
            ],
            options={
                'ordering': ['uploadTime'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20, verbose_name='菜单名称')),
                ('iconCls', models.CharField(max_length=50, verbose_name='图标样式')),
                ('checked', models.NullBooleanField(verbose_name='是否选中')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='链接')),
                ('seq', models.PositiveSmallIntegerField(verbose_name='顺序')),
                ('parentMenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='imgs.Menu')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='机构代码')),
                ('name', models.CharField(max_length=20, verbose_name='机构名称')),
                ('seq', models.PositiveSmallIntegerField(verbose_name='顺序')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddField(
            model_name='certificate',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='imgs.Org'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='imgs.Org', verbose_name='所属机构'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
