# Generated by Django 2.0.5 on 2018-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['org__code', 'fullname'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='科目代码'),
        ),
    ]
