# Generated by Django 2.0.5 on 2018-05-14 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0003_userprofile_date_disabled'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('org', 'bookedDate', 'sn')},
        ),
    ]
