# Generated by Django 2.0.5 on 2018-05-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0004_auto_20180514_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='退回时间')),
                ('reason', models.CharField(max_length=250, verbose_name='退回理由')),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': '会计科目', 'verbose_name_plural': '会计科目'},
        ),
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-bookedDate', '-sn'], 'verbose_name': '会计凭证', 'verbose_name_plural': '会计凭证'},
        ),
        migrations.AlterModelOptions(
            name='certificateimg',
            options={'ordering': ['uploadTime'], 'verbose_name': '凭证影像', 'verbose_name_plural': '凭证影像'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['seq'], 'verbose_name': '菜单', 'verbose_name_plural': '菜单'},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'ordering': ['seq'], 'verbose_name': '机构', 'verbose_name_plural': '机构'},
        ),
        migrations.AddField(
            model_name='rejectinfo',
            name='certificate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imgs.Certificate'),
        ),
    ]
