# Generated by Django 2.0.5 on 2018-05-22 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0006_rejectinfo_handled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='confirmed',
        ),
    ]
