# Generated by Django 2.0.5 on 2018-05-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0007_remove_certificate_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='rejected',
            field=models.BooleanField(default=False, verbose_name='是否退回'),
        ),
    ]
