# Generated by Django 2.0.5 on 2018-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0008_certificate_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateimg',
            name='description',
            field=models.CharField(blank=True, default='未录入', max_length=200, verbose_name='影像说明'),
        ),
    ]
