# Generated by Django 2.0.5 on 2018-05-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0009_certificateimg_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rejectinfo',
            name='reason',
            field=models.TextField(verbose_name='退回理由'),
        ),
    ]
