# Generated by Django 2.0.5 on 2018-06-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0011_param'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='account',
        ),
        migrations.AddField(
            model_name='certificate',
            name='accountCode',
            field=models.CharField(default='1001', max_length=10, verbose_name='科目代码'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='accountName',
            field=models.CharField(default='未指定', max_length=50, verbose_name='科目名称'),
        ),
    ]
