# Generated by Django 2.0.5 on 2018-10-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0015_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='roles',
            field=models.CharField(default='user', max_length=30, verbose_name='权限'),
            preserve_default=False,
        ),
    ]
