# Generated by Django 2.0.5 on 2018-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0016_menu_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', '系统管理员'), ('user', '录入人'), ('viewer', '查看人')], max_length=10, verbose_name='角色'),
        ),
    ]
