# Generated by Django 2.0.5 on 2018-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgs', '0017_auto_20181108_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='sn',
            field=models.PositiveSmallIntegerField(verbose_name='流水号'),
        ),
    ]
